name: CI

permissions:
  contents: write

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    name: ci-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: easy-install/easy-setup@v1
        with:
          url: |-
            https://github.com/ahaoboy/wiztree-metafile
            https://github.com/ahaoboy/metafile-viz

      - name: run wiztree unix
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          wiztree-metafile / -i "/proc" -o ${{ matrix.os }}.json
          ls -lh ${{ matrix.os }}.json

      - name: run wiztree windows
        shell: powershell
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          wiztree-metafile c:/ -o ${{ matrix.os }}.json
          ls ${{ matrix.os }}.json

      - name: run metafile-viz
        run: |
          metafile-viz ${{ matrix.os }}.json -o ${{ matrix.os }}.png --width 1920 --height 1080
          ls -lh ${{ matrix.os }}.png

      - name: Upload PNG
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}.png
          path: ${{ matrix.os }}.png

      - name: Upload JSON
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}.json
          path: ${{ matrix.os }}.json

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ matrix.os }}.png,${{ matrix.os }}.json"
          allowUpdates: true
          tag: "nightly"
          makeLatest: false
